version: 0.2
phases:
  install:
    commands:
      - curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-app
      - aws eks update-kubeconfig --name Demo --region $AWS_REGION
      - helm upgrade --install my-app ./helm --namespace default --set image.repository=$REPO_URI,image.tag=$IMAGE_TAG
artifacts:
  files: []
